project:
  type: website
  output-dir: docs

website:
  title: "Irshad Ul Haq"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Research.qmd

format:
  html:
    theme:
      - minty
      - brand
      - solar
    css: styles.css
    toc: true
    page-layout: full


